# Generated by Django 3.2.7 on 2021-09-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210925_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='clinic',
            name='task1',
            field=models.CharField(default='Округ', max_length=20, verbose_name='Округ'),
        ),
    ]
